# 
# Synthesis run script generated by Vivado
# 

set_param gui.test TreeTableDev
set_param xicom.use_bs_reader 1
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000

create_project -in_memory -part xc7z020clg484-1
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/Antonin/FPGA_project/Test/Test.cache/wt [current_project]
set_property parent.project_path C:/Users/Antonin/FPGA_project/Test/Test.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part em.avnet.com:zed:part0:1.2 [current_project]
read_vhdl -library xil_defaultlib {
  C:/Users/Antonin/FPGA_project/Globe_persistance_retinienne/Globe_persistance_retinienne.srcs/sources_1/new/packages/globe_package.vhd
  C:/Users/Antonin/FPGA_project/Globe_persistance_retinienne/Globe_persistance_retinienne.srcs/sources_1/new/packages/image_package.vhd
  C:/Users/Antonin/FPGA_project/Globe_persistance_retinienne/Globe_persistance_retinienne.srcs/sources_1/new/display_package.vhd
  C:/Users/Antonin/FPGA_project/Test/Test.srcs/sources_1/new/column_reader.vhd
  C:/Users/Antonin/FPGA_project/Globe_persistance_retinienne/Globe_persistance_retinienne.srcs/sources_1/new/send_pixel.vhd
  C:/Users/Antonin/FPGA_project/Globe_persistance_retinienne/Globe_persistance_retinienne.srcs/sources_1/new/send_to_stripe.vhd
  C:/Users/Antonin/FPGA_project/Test/Test.srcs/sources_1/new/display_test.vhd
}
read_xdc C:/Users/Antonin/FPGA_project/Test/Test.srcs/constrs_1/new/top.xdc
set_property used_in_implementation false [get_files C:/Users/Antonin/FPGA_project/Test/Test.srcs/constrs_1/new/top.xdc]

catch { write_hwdef -file display_test.hwdef }
synth_design -top display_test -part xc7z020clg484-1
write_checkpoint display_test.dcp
catch { report_utilization -file display_test_utilization_synth.rpt -pb display_test_utilization_synth.pb }
