webtalk_init -webtalk_dir /home/phhorrei/perso/fablab/zybo_globe/source/vivado/hw/zybo_bsd/zybo_bsd.sdk/webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Fri Apr 10 08:12:57 2015" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2014.4" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2014.4" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "174120980_174171490_210595434_246" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "9i2841greaj13aalhebq4qhfci" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2014.4_3" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "3" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Debian" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Debian GNU/Linux 8.0 (jessie)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-3230M CPU @ 2.60GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2879.703 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1428614085000" -context "sdk\\\\hardware/1428614085000"
webtalk_add_data -client sdk -key isZynq -value "true" -context "sdk\\\\hardware/1428614085000"
webtalk_add_data -client sdk -key Processors -value "2" -context "sdk\\\\hardware/1428614085000"
webtalk_add_data -client sdk -key VivadoVersion -value "2014.4" -context "sdk\\\\hardware/1428614085000"
webtalk_add_data -client sdk -key Arch -value "zynq" -context "sdk\\\\hardware/1428614085000"
webtalk_add_data -client sdk -key Device -value "7z010" -context "sdk\\\\hardware/1428614085000"
webtalk_add_data -client sdk -key IsHandoff -value "true" -context "sdk\\\\hardware/1428614085000"
webtalk_add_data -client sdk -key uid -value "1428614120000" -context "sdk\\\\bsp/1428614120000"
webtalk_add_data -client sdk -key hwid -value "1428614085000" -context "sdk\\\\bsp/1428614120000"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\bsp/1428614120000"
webtalk_add_data -client sdk -key apptemplate -value "zynq_fsbl" -context "sdk\\\\bsp/1428614120000"
webtalk_add_data -client sdk -key uid -value "1428614123000" -context "sdk\\\\application/1428614123000"
webtalk_add_data -client sdk -key hwid -value "1428614085000" -context "sdk\\\\application/1428614123000"
webtalk_add_data -client sdk -key bspid -value "1428614120000" -context "sdk\\\\application/1428614123000"
webtalk_add_data -client sdk -key newbsp -value "true" -context "sdk\\\\application/1428614123000"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\application/1428614123000"
webtalk_add_data -client sdk -key apptemplate -value "zynq_fsbl" -context "sdk\\\\application/1428614123000"
webtalk_transmit -clientid 3353111258 -regid "174120980_174171490_210595434_246" -xml /home/phhorrei/perso/fablab/zybo_globe/source/vivado/hw/zybo_bsd/zybo_bsd.sdk/webtalk/usage_statistics_ext_sdk.xml -html /home/phhorrei/perso/fablab/zybo_globe/source/vivado/hw/zybo_bsd/zybo_bsd.sdk/webtalk/usage_statistics_ext_sdk.html -wdm /home/phhorrei/perso/fablab/zybo_globe/source/vivado/hw/zybo_bsd/zybo_bsd.sdk/webtalk/sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
